### ISSUE TITLE
kr.kgaons.armorplus.events

### ISSUE THREAD

**Issue by RanolP** [SkyLightQP/ArmorPlus#10]
1. GUIEvent와 MainEvent는 이 클래스의 용도를 명확하게 나타내지 않으므로 GuiListener 혹은 InventoryListener와 PlayerListener 등의 이름으로 변경할 것을 권장함.
1. GUIEvent#onClick에 28~35 라인의 의미 없는 코드를 삭제하는 것을 권장함.

**Comment by SkyLightQP** [comment]
2 -> 디버그 코드
