### ISSUE TITLE
events/GUIEvent.java

### ISSUE THREAD

**Issue by RanolP** [SkyLightQP/ArmorPlus#7]
1. 이는 좋지 않은 PascalCase입니다. :(
1. Listener를 상속했으므로 GuiListener가 더 바른 표현입니다.
1. 29~33 라인의 첫번째 if는 의미가 없고, 부등호를 사용하여 대체가 가능합니다.
1. 어차피 e.setCancelled(true);를 호출한다면 비교는 대체 왜 한거죠...?
1. 44/45 라인의 로컬 변수의 네이밍을 고치세요.
1. 46 라인은 의미 없는 코드입니다.
1. 50~63 라인을 감싼 try ~ catch는 의미가 있나요?
1. 53~60 라인의 switch에 default 문을 추가해 방어적 프로그래밍을 하세요.

**Comment by SkyLightQP** [comment]
개발 중인 플러그인이므로 디버그 코드가 있다는걸 명시해둡시다.
